web:
    build: .
    links:
    - db
    ports:
    - "8080:8080"
db:
    image: postgres
    environment:
    - POSTGRES_DB=inshop
    - POSTGRES_USER=inshop
    - POSTGRES_PASSWORD=inshop
    - PGDATA=/data
    volumes:
    - /data:/data
